language: android
android:
  components:
  - tools
  - platform tools
  - tools
  - add-on
  - extra
  # The build tools version for the project
  - build-tools-26.1.1
  # SDK version used to compile the project
  - android-28
  
  # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - add-on-google_apis-google-28

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-28
  
