language: android
android:
  components:
  - tools
  - platform tools
  - tools
  
  # The build tools version for the project
  - build-tools-26.1.1
  
  # SDK version used to compile the project
  - android-26
  
  - extra-android-support
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  
